// Все русские строки UI — в одном месте, чтобы не размазывать тексты по компонентам.
export const STR = {
  appName: 'Семейное древо',
  supabaseNotConfigured:
    'Supabase не настроен: заполните VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY в .env.local и перезапустите dev-сервер.',

  // Auth
  loginTitle: 'Вход',
  registerTitle: 'Регистрация',
  emailLabel: 'Email',
  passwordLabel: 'Пароль',
  nameLabel: 'Ваше имя',
  namePlaceholder: 'Например: Леонид',
  loginButton: 'Войти',
  registerButton: 'Зарегистрироваться',
  noAccount: 'Нет аккаунта?',
  haveAccount: 'Уже есть аккаунт?',
  toRegister: 'Зарегистрироваться',
  toLogin: 'Войти',
  checkEmailTitle: 'Подтвердите почту',
  checkEmailText: 'Мы отправили письмо со ссылкой подтверждения на',
  checkEmailHint: 'Если письма нет — проверьте папку «Спам».',
  signOut: 'Выйти',

  // Восстановление пароля
  forgotPassword: 'Забыли пароль?',
  resetTitle: 'Восстановление пароля',
  resetHint: 'Укажите email — пришлём ссылку для смены пароля.',
  resetSend: 'Отправить ссылку',
  resetSentTitle: 'Проверьте почту',
  resetSentText: 'Если аккаунт с таким email существует, мы отправили ссылку для смены пароля на',
  backToLogin: 'Вернуться ко входу',
  newPasswordTitle: 'Новый пароль',
  newPasswordLabel: 'Новый пароль',
  newPasswordRepeat: 'Повторите пароль',
  newPasswordSave: 'Сохранить пароль',
  passwordsMismatch: 'Пароли не совпадают',
  passwordChanged: 'Пароль изменён',
  passwordTooShort: 'Не короче 6 символов',
  showPassword: 'Показать пароль',
  hidePassword: 'Скрыть пароль',
  recoveryLinkInvalid: 'Ссылка недействительна или устарела — запросите новую',
  recoveryPreparing: 'Проверяем ссылку…',

  // Pending / rejected
  pendingTitle: 'Заявка на рассмотрении',
  pendingText:
    'Ваш аккаунт создан. Администратор должен одобрить его — после этого откроется доступ к семейному древу.',
  rejectedTitle: 'Заявка отклонена',
  rejectedText: 'Администратор отклонил вашу заявку. Если это ошибка — свяжитесь с ним.',
  checkAgain: 'Проверить ещё раз',
  stillPending: 'Пока не одобрено. Попробуйте позже.',

  // Admin
  adminNav: 'Заявки и участники',
  pendingRequestsTitle: 'Ожидают одобрения',
  adminTitle: 'Участники',
  approve: 'Одобрить',
  reject: 'Отклонить',
  makeAdmin: 'Сделать админом',
  revokeAdmin: 'Снять админа',
  statusPending: 'Ожидает',
  statusApproved: 'Одобрен',
  statusRejected: 'Отклонён',
  roleAdmin: 'админ',
  colName: 'Имя',
  colEmail: 'Email',
  colDate: 'Регистрация',
  colStatus: 'Статус',
  colActions: 'Действия',
  colPersonLink: 'Карточка на древе',
  notLinked: '— не привязана —',
  noProfiles: 'Пока никто не зарегистрирован.',

  // Доска
  addPerson: '+ Добавить родственника',
  createPersonTitle: 'Новый родственник',
  editPersonTitle: 'Карточка родственника',
  firstName: 'Имя',
  middleName: 'Отчество',
  lastName: 'Фамилия',
  maidenName: 'Девичья фамилия',
  gender: 'Пол',
  genderM: 'Мужской',
  genderF: 'Женский',
  genderUnset: 'Не указан',
  birthDate: 'Дата рождения',
  deathDate: 'Дата смерти',
  yearOnly: 'только год',
  yearPlaceholder: 'Год, напр. 1917',
  birthPlace: 'Место рождения',
  residence: 'Где жил(а)',
  education: 'Образование',
  occupation: 'Кем работал(а)',
  achievements: 'Достижения',
  militaryStatus: 'Воинская служба',
  militaryUnset: 'Не указано',
  militaryNotServed: 'Не служил(а)',
  militaryServed: 'Служил(а)',
  militaryFought: 'Воевал(а)',
  militaryNotes: 'Боевой путь',
  militaryNotesHint: 'Годы, войны, части, награды…',
  veteranBadge: 'Участник боевых действий',
  bio: 'Биография, заметки',
  save: 'Сохранить',
  cancel: 'Отмена',
  createAction: 'Добавить',
  connectTitle: 'Какая это связь?',
  spouses: 'супруги',
  relExists: 'Такая связь уже есть',
  posSaveError: 'Не удалось сохранить расположение',
  boardEmpty:
    'На доске пока никого. Нажмите «Добавить родственника» или дважды кликните по пустому месту.',

  // Контекстное меню и связывание
  openCard: 'Открыть карточку',
  back: 'Назад',
  addRelativeMenu: 'Добавить родственника',
  roleFather: 'Отец',
  roleMother: 'Мать',
  roleSon: 'Сын',
  roleDaughter: 'Дочь',
  roleHusband: 'Муж',
  roleWife: 'Жена',
  roleSpouse: 'Супруг(а)',
  roleBrother: 'Брат',
  roleSister: 'Сестра',
  linkExisting: 'Связать с…',
  linkModeHint: 'Кликните по человеку, с которым установить связь · Esc — отмена',
  edit: 'Редактировать',
  needParentsHint: 'Сначала добавьте родителей',
  hasFatherHint: 'Отец уже указан',
  hasMotherHint: 'Мать уже указана',
  deleteRelation: 'Удалить связь',
  confirmDelete: 'Точно удалить?',
  markAsEx: 'Пометить как бывших',
  unmarkAsEx: 'Снова супруги',

  // Сайдбар
  kinshipTitle: 'Родство',
  groupParents: 'Родители',
  groupSpouses: 'Супруг(а)',
  groupChildren: 'Дети',
  groupSiblings: 'Братья и сёстры',
  groupOtherKin: 'Другая родня',
  addRelation: 'Добавить связь',
  youBadge: 'Это вы',
  pickPersonTitle: 'Выберите человека',
  searchPlaceholder: 'Поиск по имени…',
  nothingFound: 'Никого не нашлось',
  close: 'Закрыть',

  exportExcel: 'Экспорт в Excel',
  exportGedcom: 'Экспорт GEDCOM',
  importGedcom: 'Импорт GEDCOM',
  importError: 'Не удалось импортировать файл',
  moreActions: 'Ещё',
  autoLayout: 'Разложить как дерево',
  birthdaysTitle: 'Дни рождения',
  surnamesTitle: 'Фамильные линии',
  showAllSurnames: '← Показать все',
  exportPng: 'Скачать картинкой',
  search: 'Поиск',
  layoutDone: 'Дерево разложено',
  pngError: 'Не удалось сохранить картинку',

  // Права и замечания
  editRestricted: 'Карточку может изменять её автор, сам человек или админ',
  writeToAdmin: 'Написать админу',
  editRequestTitle: 'Замечание к карточке',
  editRequestPlaceholder: 'Что нужно поправить? Сообщение увидят админ и автор карточки.',
  send: 'Отправить',
  sentOk: 'Отправлено',
  notesTitle: 'Замечания',
  markDone: 'Готово',
  adminNotesTitle: 'Открытые замечания к карточкам',
  noOpenNotes: 'Открытых замечаний нет',
  deletePerson: 'Удалить с доски',
  deletePersonTitle: 'Удалить безвозвратно?',
  deleted: 'Удалено',

  // Фотографии
  photosTitle: 'Фотографии',
  uploadHintDrop: 'Перетащите фото сюда или ',
  chooseFiles: 'выберите файлы',
  setAvatar: 'Сделать аватаром',
  avatarSet: 'Аватар обновлён',
  captionLabel: 'Подпись',
  deletePhoto: 'Удалить фото',
  noPhotos: 'Пока нет фотографий',
  fileTooLarge: 'Файл больше 15 МБ',
  notAnImage: 'Это не изображение',
  uploadError: 'Не удалось загрузить фото',

  // Общее
  saved: 'Сохранено',
  loadError: 'Не удалось загрузить данные',
  saveError: 'Не удалось сохранить',

  // Ошибки auth
  errInvalidCredentials: 'Неверный email или пароль',
  errEmailNotConfirmed: 'Email не подтверждён — проверьте почту, мы отправляли письмо со ссылкой',
  errUserExists: 'Пользователь с таким email уже зарегистрирован',
  errPasswordShort: 'Пароль должен быть не короче 6 символов',
  errRateLimit: 'Слишком много попыток — подождите немного и попробуйте снова',
  errGeneric: 'Что-то пошло не так, попробуйте ещё раз',
} as const

// Шаблонные строки
export const fmt = {
  parentOf: (parent: string, child: string) => `${parent} — родитель: ${child}`,
  spousePair: (a: string, b: string) => `${a} и ${b} — супруги`,
  exSpousePair: (a: string, b: string) => `${a} и ${b} — бывшие супруги`,
  kinOf: (name: string, term: string, other: string) => `${name} — ${term}: ${other}`,
  uploading: (done: number, total: number) => `Загрузка ${done} из ${total}…`,
  importDone: (p: number, r: number) => `Добавлено: ${p} чел., ${r} связей`,
  surnameBranch: (surname: string) => `Ветка ${surname}`,
  deletePersonWarning: (name: string) =>
    `${name} будет удалён(а) вместе со всеми связями и фотографиями. Это действие нельзя отменить.`,
}
